implement java.sql.Statement
mongodb/mongo-hibernate pull request #18
Opened 2024-11-27 16:55 UTC by NathanQingyangXu

https://jira.mongodb.org/browse/HIBERNATE-16

`java.sql.Statement` is the parent class of `java.sql.PreparedStatement`, which mainly focused on parameterization. Internally after parameters passed into `PreparedStatement` are collected and resolved, the resulting SQL would still be executed in `java.sql.Statement`, including:

- ResultSet executeQuery(String sql)
- int executeUpdate(String sql)
- boolean execute(String sql)

We have separate tickets for the first and third entry above, but the second entry is in the scope of this PR. The method parameter or `sql` could come from HQL or native MQL. Regardless, for now we simply feed it (parameterization from HQL will be done in another ticket implementing `java.sql.PreparedStatement`) to Mongo Java driver.

The implementation internally is based on `MongoDatabase#runCommand(ClientSession, Bson)`, so we need to pass `MongoDatabase` all the way from `MongoConnectionProvider`. Currently a `@Nullable` `MongoDatabase` will be used for now and it could be changed later (when we finished discussion on how to get database somewhere).

Most of the unit testing focused on the edge cases of `int executeUpdate(String)` by mocking. After evergreen integration work is done, we might later add integration testing cases on it.

2024-11-27 16:55 UTC, NathanQingyangXu commented on build.gradle.kts
> -        option("NullAway:ExcludedFieldAnnotations", "org.mockito.InjectMocks")
found the above two options not taking effect

2024-11-27 16:56 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        throw new SQLFeatureNotSupportedException("unwrap unsupported");
simulating the message pattern elsewhere

2024-11-27 16:58 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                                + commandName);
we might need dicusson on what commands we support. The above three was copied from POC, not necessarily the best.

2025-01-07 16:05 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
As explained in the PR description, bulk write or JDBC batch processing is in the scope of https://jira.mongodb.org/browse/HIBERNATE-35.

2025-01-09 14:19 UTC, jyemin requested changes

2025-01-09 18:13 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                var documents = statement
good catch! I didn't consider order issue. Now I changed the data structure from `List<Document>` to `Set<BsonDocument>` and the order issue should be fixed.

2025-01-09 18:14 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                    Document.parse(
Yeah, I changed to `BsonDocument`. Good catch!

2025-01-09 18:24 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                        .formatted(COLLECTION_NAME);
btw, you can see `Palantir` formatting gradle plugin handles the Java docstring perfectly. It shines in complicated lambda formatting scenario though.

2025-01-10 16:01 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                        .formatted(COLLECTION_NAME);
The above native query also examplifies the necessity of multiple documents (bulk inserting). I think we'd better keep from ruloing out such common native query requirement. If we only supported CRUD API as `executeUpdate()`, our client will complain sooner or later. I think it is easy to let CRUD API and `runCommand` coexist as following:

1. if one document provided, CRUD API will be applied.
2. if multiple documents provided as the above, `runCommand` is the last resort; maybe we can substitute bulk-writing (supporting retry writing) in the future.

I am opnionated that we make native query as inviting as possible for it is the last resort and its important is more pronounced in hibernate mongoDB Dialect due to the fact that it could only showcase basic CRUD features for MongoDB is such a different animal from other dialects in SQL families.

2025-01-13 15:06 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +            });
This piece of code is used twice: in `testUpdate` and `testDelete`. Let's extract it to a `prepareData` method, or something like that.

2025-01-13 15:09 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                }
Let's guarantee the commit:

```suggestion
                try {
                    assertEquals(expectedRowCount, statement.executeUpdate(mql));
                } finally {
                    if (!autoCommit) {
                        connection.commit();
                    }
                }
```

2025-01-13 15:17 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +    private static SessionFactory sessionFactory;
I can see the IDE complaining `@NullMarked fields must be initialized` here, but not in `com.mongodb.hibernate.SessionTests`. That's because we annotated the `com.mongodb.hibernate.jdbc` package with `@NullMarked`, but did not do the same for the `com.mongodb.hibernate` package.

Let's annotate the `com.mongodb.hibernate` package with `@NullMarked`.

2025-01-13 15:35 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                        }"""
As far as I can see, these tests can get by with three documents, two of which are authored by "Leo Tolstoy". Let's reduce the number of prepared documents, as that also reduces the number of expected documents, significantly reducing the total number of lines in the test class, which makes it easier to read.

2025-01-13 18:07 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        }
Do you mean true according to the technical design, the current state of the main branch, or in scope of this PR?

2025-01-13 18:15 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
That's a good question.  Looking at `com.mongodb.client.internal.MongoDatabaseImpl#executeCommand` it looks like `timeoutMS` is ignored by the `runCommand` implementation, but that may be a bug.

I suggest we delay dealing with this issue to a separate ticket to avoid bogging down on the investigation (and testing) of this.

2025-01-13 18:17 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
I did recently add a note on the technical design to address this in the next revision.

2025-01-13 18:18 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
Can't we at least, for now, require that the connection string include a database name (e.g. `mongodb://localhost/test`, and use that as the database name?

2025-01-13 18:35 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        }
I mean our intent, which is the design. I can tell that according to the "current state of the main branch" and "in scope of this PR" the answer is "true, Mongo Hibernate does not use MongoDB transactions if auto-commit is enabled". But I am not sure is that is our intent, as the design does not give an explicit answer.

2025-01-13 18:39 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        }
OK, I see.  I suggest we leave this PR as is and add a comment to the design doc to make a decision.

2025-01-13 20:16 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        }
I added it to [Open Questions](https://docs.google.com/document/d/1yNM-DC7zF70wyCUQxViVLNzkGFGOfYH4jJZru2QbacU/edit?tab=t.0#heading=h.jbr6wn633902).

2025-01-13 20:21 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
I updated the description of [HIBERNATE-40](https://jira.mongodb.org/browse/HIBERNATE-40).

2025-01-13 20:26 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
Is adding this part of the design in scope of [HIBERNATE-40](https://jira.mongodb.org/browse/HIBERNATE-40), or should it be a separate task? I'd say that designing it requires actually trying the approach proposed, so making the design part of [HIBERNATE-40](https://jira.mongodb.org/browse/HIBERNATE-40) seems better to me.

2025-01-13 20:54 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
Note that doing as you suggest, does not address my suggestion above. With that in mind, the rest of the comment addresses the suggestion to require `database` in the connection string.

Using the `database` connection string option means that we need to change its semantics, as currently it is used only as the default value of the `authSource` connection string option (this is likely an unfortunate result of the API evolution, rather than an intended from-scratch design). Are we ready to say the following?

1. `database` is required to be specified, and is used to specify the result of {{java.sql.Connection.getSchema}, not the database to login to.
2. If a user needs to specify the database to login to, then `authSource` must be used.

If not, then we will have to come up with the design in [HIBERNATE-38](https://jira.mongodb.org/browse/HIBERNATE-38).

2025-01-13 20:57 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
This question does not block the PR, and if getting answers should not be done here, we can move the discussion. But answers are still needed, I think.

2025-01-13 22:41 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
I'm ready to say that, yes.  I've seen this use of the `database` portion of the connection in other similar situations, e.g. in Morphia.  Isn't it also how JDBC connection strings work as well in the context of Hibernate (I'm not sure what the behavior is though if it's left off.  Does the server have a notion of a default database? For MongoDB, it's typically `test`, e.g. in the MongoDB Shell.)

2025-01-14 13:53 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +    void startTransactionIfNeeded() {
I hesitated a lot previously. This method requires access to `MongoConnection`s internal fields (`autoCommit`, `clientSession`), so from encapsulation perspective, it is better to design it as `MongoConnection`'s method (`MongoStatement` needs to return `Connection` so `MongoConnection` is always accessible from it). If we move it to `MongoStatement`, it requires access to such internal implementation details of `MongoConnection`. That being said, I have no objection to move it to `MongoStatement` after making such private fields's getter method package private.

But from OOP best practise, I think it makes more sense to create transaction related methods on `Connection`, just as JDBC API has designed.

2025-01-14 13:58 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +    void startTransactionIfNeeded() {
I would highly recommend the listing lest any of these `executeXXX()` method forgets to invoke this method internally. If we built our library on top of Spring framework, a simple AOP based on method prefix would suffice.

2025-01-14 14:10 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnectionProvider.java
> +            return new MongoConnection(assertNotNull(mongoClient), clientSession);
I adopted the first alternative for the second option will be complained about by NullAway plugin.

2025-01-14 14:30 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
> Isn't it also how JDBC connection strings work

It often is, but not necessarily. There is no clear unified set of terms across different DBMSes, and on top of that, the JDBC terminology does not help (the documentation of `java.sql.Connection` uses the term "database" when referring to DBMS, and not actually any concept of a "database" maintained by that DBMS). MySQL, for example, calls "schema" what is usually referred to as "database" ("SID" in Oracle, "database" in PostgreSQL), and does not require the "schema" to be specified when connecting: https://dev.mysql.com/doc/refman/8.4/en/connecting-using-uri-or-key-value-pairs.html#:~:text=The%20default%20database%20for%20the%20connection.%20If%20no%20database%20is%20specified%2C%20the%20connection%20has%20no%20default%20database, unlike Oracle or PostgreSQL.

After looking at https://github.com/mongodb/mongo-hibernate/pull/8#discussion_r1840934095, which is the original discussion on the same topic, I realized that there is more to this, and we better properly approach it in the relevant tickets ([HIBERNATE-37](https://jira.mongodb.org/browse/HIBERNATE-37), [HIBERNATE-38](https://jira.mongodb.org/browse/HIBERNATE-38), [HIBERNATE-39](https://jira.mongodb.org/browse/HIBERNATE-39)). Thus, I am ready to resolve this discussion, unless you have objections.

P.S. I also realized that I know how to get MongoDB database names from [Table.schema](https://jakarta.ee/specifications/persistence/3.1/apidocs/jakarta.persistence/jakarta/persistence/table) for `Statement.executeUpdate`, at least: we have to extract it from the value of the first key: the first key is the command name, its value is the collection name, but if `Table.schema` is used, the collection name should be prefixed with the MongoDB database name.

2025-01-14 14:34 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
As a procedure, all the XXXAdapter classes are simply throwing exceptions invariably to allow `MongoXXX` extends it without implementing irrelevant methods. Only methods ever used in Hibernate (by code searching) will be put into `MongoXXX` classes and yeah, we differentiate the methods used by Hibernate into 3 categories:

1. methods we implemented;
2. methods we plan to implement but not in the scope of current ticket (throwing `NotYetImplementedException`, ideally with some explanation; but it is also fine without providing message);
3. methods Hibernate used but won't be supported due to the reason MongoDB is NoSQL; in this case a well-though explanation is vital.

In this case, `executeUpdate(String, int)` is never used ever in Hibernate codebase, so we don't need to override it in `MongoStatement` and default adapter implemention suffices.

2025-01-14 14:58 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/SessionTests.java
> +        assertDoesNotThrow(() -> session.doWork(connection -> {}));
I assumed, you wanted to check if `session` stays usable after committing. So `session.doWork` did not seem out of place to me.

2025-01-14 15:02 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/SessionTests.java
>      }
This is integration test, `MongoConnectionTests` is purely unit testing.  Due to bootstrapping reason (in the future when JDBC flow is done and we could focus on higher level Hibernate CRUD testing these internal JDBC stuff would be tested indirectly), currently the `Session#doWork()` is the only option to test JDBC internal flow so it seems reasonable to put such JDBC integration testing into `SessionTests`.

I refactored this class by creating a new `@Nested` testing class focusing on `doWork()` and moved the previously `createConnection` into it, together with the new `createStatement()` testing case. In the future `createPreparedStatement()` will be put there as well.

2025-01-14 15:03 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +            throw new ClosedSQLException(this.getClass());
I've deleted this class which is only meaningful for unit testing validation purpose and will confuse future developers all the time.

2025-01-14 15:28 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
btw, we could also take a look at MongoDB's JDBC Driver repo to get some inspiration: https://github.com/mongodb/mongo-jdbc-driver. It uses the database in connection string and it implements OIDC to cover edge case. I don't think we need to follow strictly JDBC specifics for in the first place it is really confusing and impairs our product for it requires knowledge spanning both SQL and MongoDB NoSQL.

Another thing we need to keep in mind is how to get database from our Client Customizer which has freedom to ignore the configured connection string. All in all, we could delay the decision later (currently even such ugly default database name suffices for M1), but I also hope we don't make it too complicated. At least for one thing, native MQL (an important feature of our product) won't contain db name and only collection name is provided. So a global default db name is required.

2025-01-14 15:30 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
My gut feeling is `runCommand` is good choice for now. It covers everything, not necessarily the most performant for is enough for the time being.

2025-01-14 15:45 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        return new MongoStatement(mongoClient, clientSession, this);
The other `createPreparedStatement(int resultSetType, int result SetConcurrency) is used in Hibernate at https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java#L149.

But this method is never used in Hibernate ORM. For that reason, I deleted it from `MongoConnection` class.

2025-01-14 15:53 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +        }
I changed it to
```
@Test
        @DisplayName("SQLException is thrown when database access error occurs")
        void testSQLExceptionThrownWhenDBAccessFailed(@Mock(answer = RETURNS_SMART_NULLS) MongoDatabase mongoDatabase) {
            // given
            doReturn(mongoDatabase).when(mongoClient).getDatabase(anyString());
            var dbAccessException = new RuntimeException();
            doThrow(dbAccessException).when(mongoDatabase).runCommand(same(clientSession), any(BsonDocument.class));
            String mql =
                    """
                    {
                          delete: "orders",
                          deletes: [ { q: { status: "D" }, limit: 1 }, { q: { outOfStock: true }, limit: 0 } ]
                       }
                    """;

            // when && then
            var sqlException = assertThrows(SQLException.class, () -> mongoStatement.executeUpdate(mql));
            assertEquals(dbAccessException, sqlException.getCause());
        }
```

2025-01-14 18:50 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +            var mql =
definitively. It is too sloppy. I deleted `mql` and copied some example mqls from mongoDB doc website.

2025-01-14 19:16 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +            return map.entrySet().stream().map(entry -> Arguments.of(entry.getKey(), entry.getValue()));
Thanks. Improved dramatically. Just one caveat. The last statement should be:
```
.map(entry -> Arguments.of(entry.getKey(), entry.getValue()));
```
otherwise compiler won't complain but runtime exception will be thrown.

2025-01-14 19:34 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +                     }""";
not much reason other than that the auto-formatting `Palantir` plugin won't do a good job on text block. yeah, that is not an excuse not to make them look a little bit better or consistent. It depends on whether the plugin deems my change is valid or not; if not it will reformat automatically so I have no choice.

At least I could make consistent usage of `\n` in `MongoStatementTests`.  But for other format changes like indentation, the plugin dictates in ad-hoc way overwriting my local changes. Really annoying. A good example of the cons of auto-formatting approach.

2025-01-14 19:36 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                                        .formatted(COLLECTION_NAME));
I tried multiple ways without success fighting with the plugin. Whenever I put it adjacent to the ending text block, after running `spotlessJavaApply`, it will end up as above. If you were interested, you could try locally to see whether there is some way out.

The only way currently I could think of is to use hard-coded collection names throughout the class.

2025-01-14 19:42 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +            });
done

2025-01-14 19:44 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                }
I am afraid the above change won't work for the commit() has to happen BEFORE assertion statements, otherwise empty result will be returned.

2025-01-14 19:54 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                        }"""
good point! Yeah, 3 docs suffice.

2025-01-14 20:15 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
For the time being I moved the DB static final variable from `MongoStatement` to `MongoConnection`.

2025-01-14 20:21 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +    private static final String DATABASE = "mongo-hibernate-test";
> I'm ready to say that, yes. I've seen this use of the `database` portion of the connection in other similar situations, e.g. in Morphia. Isn't it also how JDBC connection strings work as well in the context of Hibernate (I'm not sure what the behavior is though if it's left off. Does the server have a notion of a default database? For MongoDB, it's typically `test`, e.g. in the MongoDB Shell.)

In JDBC or Hibernate, JDBC URL is self-contained connection target. I don't think there is default DB mechanism. What really matters is JDBC Connection. For more details, we can refer to https://www.baeldung.com/java-jdbc-url-format.

My opinion is we don't need to follow strictly JDBC convention for MongoDB is not vanillar JDBC mechanism. 

I think using `test` as default DB for shell makes sense for it is mainly for testing purpose; but our library should target production code and I think it is sensible to let user decide it explicitly, just as Spring Data MongoDB does. It is one of the key customizations our user should make from my understanding.

2025-01-15 17:03 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        return new MongoStatement(mongoClient, clientSession, this);
`MongoConnection.prepareStatement(String mql, int resultSetType, int resultSetConcurrency)` haven't been implemented so far (it throws `NotYetImplementedException`). But we will have to think about what to do with its argument when implementing it.

2025-01-15 17:29 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +            return map.entrySet().stream().map(entry -> Arguments.of(entry.getKey(), entry.getValue()));
> otherwise compiler won't complain but runtime exception will be thrown

Sorry, yes, of course

2025-01-15 18:15 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +        return new MongoStatement(mongoClient, clientSession, this);
It belongs to next `java.sql.PreparedStatement` PR scope and I think we only need to remove the unused `createStatement(int resultSetType, int resultSetConcurrency)` in this PR. I will handle `prepareStatement(String mql, int resultSetType, int resultSetConcurrency)` in the next PR for sure. It depends on how Hibernate is gonna use it.

2025-01-15 18:17 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementTests.java
> +            return map.entrySet().stream().map(entry -> Arguments.of(entry.getKey(), entry.getValue()));
np. I love your suggestion of code improvement, even though it is testing code.

2025-01-15 19:11 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +    void startTransactionIfNeeded() {
> requires access to MongoConnections internal fields (autoCommit, clientSession)

I don't think that's true. Here is the verbatim implementation of the `startTransactionIfNeeded` method in `MongoStatement`:

```java
private void startTransactionIfNeeded() throws SQLException {
    if (!mongoConnection.getAutoCommit() && !clientSession.hasActiveTransaction()) {
        clientSession.startTransaction();
    }
}
```

As you may see, it does not require `mongoConnection` to open more than it already does:

1. `getAutoCommit` is a `public` method required by the `Connection` interface.
2. `clientSession` is already an instance field of `MongoStatement`.

When `startTransactionIfNeeded` is on `MongoConnection`, it has to be package-access, but when it is on `MongoStatement`, it can be private. That is, by moving it we increase encapsulation.

I suspect, however, that we will have to make `MongoStatement.startTransactionIfNeeded` non-private anyway when implementing `PreparedStatement`. As a result of this, and your disinclination to move the method to `PreparedStatement`, I am marking this suggestion as optional. Feel free to resolve it without any changes.

2025-01-15 19:27 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +    void startTransactionIfNeeded() {
yeah, good point. I missed that `Connection#getAutoCommit()` is public. Seems moving it to `MongoStatement` makes perfect sense then. I don't think it requires non-private visibility there for `PreparedStatement` won't invoke it and all the `executeXXX()` methods reside in `MongoStatement` and are the only invoker of it.

2025-01-15 19:33 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +    void startTransactionIfNeeded() {
I moved it into `MongoStatement` without some necessary changes (mainly due to the fact that `MongoConnection#getAutoCommit()` might throw `SqlException`). Thanks for the insight. I think the change makes lots of sense.

2025-01-15 20:35 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
So you are saying that the distinction between

```java
// ConnectionAdapter.prepareStatement(String mql, int autoGeneratedKeys)
throw new SQLFeatureNotSupportedException("prepareStatement not implemented")
```
vs
```java
// MongoConnection.prepareStatement(String mql, int autoGeneratedKeys)
throw new SQLFeatureNotSupportedException("Auto-generated key from MongoDB server side unsupported")
```

is vital. But I don't see how that can be the case:

1. The only difference is the exception message, which is not intended to be used to control the flow, i.e., it is intended to be consumed by humans merely as a clarification: "not implemented" (and not planned to be) vs "unsupported" (and not planned to be). Why do you consider this distinction vital?
2. There is no way for us to make sure we use the "unsupported" exception message for all methods that we can't implement (or deem not worth implementing), despite them being called by Hibernate ORM. That is because if we upgrade the Hibernate ORM dependency, and it starts using a JDBC method we can't implement, which it previously hasn't used, in such a way that Mongo Hibernate works nonetheless (just like it is currently the case for `ConnectionAdapter.prepareStatement(String mql, int autoGeneratedKeys)`), there is no mechanism that will inform us about such a method, and it will stay throwing an exception with the "not implemented" message instead of being overridden to throw the "unsupported" message.

2025-01-15 20:37 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
> I even intended to only include methods Hibernate never used in adapter, but later on I think that manual labour is not necessary and blindly throwing exception there suffices

_"manual labour is not necessary"_ is one of the reasons I am arguing for us to stop making the distinction between "not implemented" and "unsupported".

2025-01-15 20:41 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
@NathanQingyangXu Do you have an answer to https://github.com/mongodb/mongo-hibernate/pull/18#discussion_r1913767223?

2025-01-15 20:58 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +    private static SessionFactory sessionFactory;
when I added `@NullMarked` to `com.mongodb.hibernate`, IDE complains about both classes. Not sure how to solve the issue.
I think the workaround is to add `@Nullable` to these variables just treating them as normal non-test classes.

2025-01-15 21:02 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +    private static SessionFactory sessionFactory;
> IDE complains about both classes

That's as expected. The fact that it did not complain about `com.mongodb.hibernate.SessionTests` got me into the realization that the `com.mongodb.hibernate.jdbc` package wasn't annotated, despite having to be.

2025-01-15 21:03 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +    private static SessionFactory sessionFactory;
I fixed both after adding the `@NullMarked` annotation to `com.mongodb.hibernate`. Note that given the integrationTest PR got merged into main, the `StatementIntegrationTest` has moved to `src/integrationTest` folder. The original `src/test` is reserved for pure unit testing cases which doesn't require external mongodb service deployment.

2025-01-15 21:09 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
I agree there is such possibility though Hibernate's JDBC usage is pretty stable, which is the reason I made the distinction. I admit it is not perfect. The whole point of the labour intensive distinction is simply to provide a more meaningful exception message. Of course if such labour is not justified, it would save lots of labour.

If you are certain no need for such distinction, I am ok with removing all those `unsupported` methods from `MongoXXX` classes.

2025-01-15 21:14 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoStatement.java
> +                    .runCommand(clientSession, command)
yeah, I agree. Feel free to add design. Jeff implemented it in POC project as following:
```
@Override
    public int executeUpdate(final String sql) throws SimulatedSQLException {
        Assertions.notNull("sql", sql);
        throwExceptionIfClosed();
        BsonDocument command = BsonDocument.parse(sql);

        replaceParameterMarkers(command);
        logAndRecordCommand(command);

        String commandName = command.getFirstKey();
        MongoCollection<BsonDocument> collection =
                mongoDatabase.getCollection(command.getString(commandName).getValue(), BsonDocument.class);
        switch (commandName) {
            case "insert":
                BsonDocument document = command.getArray("documents").get(0).asDocument();
                collection.insertOne(clientSession, document);
                return 1;
            case "update":
                BsonDocument updateDocument = command.getArray("updates").get(0).asDocument();
                UpdateResult updateResult = !updateDocument.getBoolean("multi").getValue()
                        ? collection.updateOne(
                                clientSession, updateDocument.getDocument("q"), updateDocument.getDocument("u"))
                        : collection.updateMany(
                                clientSession, updateDocument.getDocument("q"), updateDocument.getDocument("u"));
                return (int) updateResult.getModifiedCount();
            case "delete":
                BsonDocument deleteDocument = command.getArray("deletes").get(0).asDocument();
                DeleteResult deleteResult = deleteDocument.getNumber("limit").intValue() == 1
                        ? collection.deleteOne(clientSession, deleteDocument.getDocument("q"))
                        : collection.deleteMany(clientSession, deleteDocument.getDocument("q"));
                return (int) deleteResult.getDeletedCount();
            default:
                throw new NotSupportedSQLException("unknown command: " + commandName);
        }
    }
```

2025-01-15 21:16 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                                        .formatted(COLLECTION_NAME));
It seems the only issue with `Palantir` is the begining `'''` is placed on a new line with indentation. I manually make the ending `'''` align vertically with it and now they seem looking better now.

2025-01-15 21:55 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                                        .formatted(COLLECTION_NAME));
If the issue with the formatting is caused by the auto-formatting tool, then there is not much to do. And if "flying" `.formatted(COLLECTION_NAME));` is a result of that, we should not give up on using this method. Feel free to reinstate its usage, I won't complain about the multiline string formatting anymore.

2025-01-15 21:56 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                                        .formatted(COLLECTION_NAME));
But if you do decide to leave the code without calls to `formatted`, then let's remove the `// private static final String COLLECTION_NAME = "books";` line.

2025-01-15 22:08 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoStatementIntegrationTests.java
> +                                        .formatted(COLLECTION_NAME));
Yeah, it is overlooked

2025-01-15 22:09 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
I removed such methods from both `MongoConnection` and `MongoStatement` with some javadoc change.

2025-01-15 22:18 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/StatementAdapter.java
> +    }
👍

2025-01-15 22:59 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/SessionTests.java
>      }
> This is integration test

The former `SessionTests.testCreateStatement`, which is now `SessionTests.DoWorkTests.createConnectionTest` was and still is a unit test: it does not need a MongoDB deployment, which is why you haven't moved it to `integrationTest`.


### createStatementTest

```
@Test
void createStatementTest() {
    assertDoesNotThrow(() -> assertNotNull(session).doWork(Connection::createStatement));
}
```

Is indeed a test of the `Connection.createStatement` method, which is why it should be in `MongoConnectionTests`:


```java
@Test
void createStatementTest() throws SQLException {
    mongoConnection.createStatement().close();
}
```

### createConnectionTest

```java
@Test
void createConnectionTest() {
    assertDoesNotThrow(() -> assertNotNull(session).doWork(connection -> {}));
}
```

Is actually a test of `Session.doWork`, which happens to create a connection. I agree with its location in `SessionTests.DoWorkTests`, but I suggest naming it `doWorkTest` what it actually is testing.


P.S. I understand why you referred to `SessionTests.testCreateStatement`/`SessionTests.DoWorkTests.createConnectionTest` as "integration test" - it involves both `Session` and `Connection` without either being mocked. But you yourself did not use this interpretation of the "integration test" concept when introduced the `integrationTest` directory. And as for me, I have never seen this interpretation as practically meaningful.

2025-01-15 23:03 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/SessionTests.java
>      }
This discussion is the only thing that stops me from approving the PR. It is definitely far from being a hill I would die on, but I would still like to hear back your thoughts (maybe I even managed to convince you in something).

2025-01-16 00:02 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/SessionTests.java
>      }
I agree they are not useful. The other `createTransactionTest()` used to be useful to prove something, but this `doWorkTest` goes nowhere. We have `StatementIntegrationTest` already, so no need to tap into the JDBC backdoor of `Session#doWork()` further.

I removed the meaningless `testCreateStatement()` and renamed the other `createConnectionTest` to `doWorkTest`. Of course you are right.

2025-01-16 13:42 UTC, stIncMale approved these changes

2025-01-16 14:38 UTC, jyemin approved these changes

2025-01-16 14:38 UTC, merged