implement java.sql.DatabaseMetaData
mongodb/mongo-hibernate pull request #22
Opened 2024-12-06 02:54 UTC by NathanQingyangXu

Most of the `java.sql.DatabaseMetaData` used by Hibernate is irrelevant to Mongo Dialect (vast majority is for DDL processing, which has no counterpart in Mongo Dialect; the only DDL in Mongo Dialect is for index and unique constraint creation in the last milestone), except for the following items:

- mongodb version (if below 6.0, MongoDialect will complain by throwing exception)
- boolean supportsBatchUpdates(), which is vital to MongoDB Dialect

The current implementation is based on running `buildinfo` command to `admin` database.

Finally we could get rid of the deprecated default constructor of `MongoDialect`.

2025-01-22 23:27 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoConnectionTests.java
> +        class TransactionTests {
Why were `MongoConnectionTests.TransactionTests` moved to `MongoConnectionTests.CloseTests.TransactionTests`, and `GetMetaDataTests` created in `CloseTests`? Neither seems right.

2025-01-22 23:35 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +            throw new SQLException("Failed to get metadata", e);
Hibernate ORM calls `MongoConnection.getMetaData` from `JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata`, and erases all the useful information from any exception thrown by `getMetaData` when it logs that exception [`log.unableToObtainConnectionMetadata( e )`](https://github.com/hibernate/hibernate-orm/blob/d0f3b674a665b290d940568ed88921bb3f8115c0/hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java#L377). As a result, when Hibernate ORM is instructed to extract metadata (`JdbcSettings.ALLOW_METADATA_ON_BOOT` is `true`), and fails to do so (for example, because it failed to connect to a MongoDB deployment), it fails to be instantiated without any meaningful exception thrown to an application or logged.

To fix this issue, let's log `e` at the `ERROR` level before wrapping it in `SQLException` and throwing.

2025-01-22 23:45 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoConnectionTests.java
>              }
There are multiple tests like this one for other `MongoConnection` methods. They are all similar to each other and different from the new method in the:

- display name pattern
- test method name pattern
- implementation pattern

1. Let's make all of these tests uniform: same display name / test method name pattern, same implementation pattern.
2. I pointed out to a similar issue previously. I think, this is something that can be taken care before submitting a PR into review.

2025-01-23 14:57 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> -    }
Seems we don't need to support these types for we had decided not to support gridfs mapping. Another subtle reason is if we didn't delete them, we need to change `NotYetImplementatedException` as a subclass of `SQLException` for Hibernate internally has a subtle logic to invoke `Connection#createBlob()` to tell whether dialect supports blob (by only catching SQLException). So without introducing another `NotYetImplementedSQLException` our integration testing case would fail. I think simply removing Blob/Clob support might be better. I made the change to remove both from https://github.com/mongodb/mongo-hibernate/pull/24.

2025-01-23 15:04 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> -        checkClosed();
I must overlooked something when I made the change long time ago. Added back. Thanks.

2025-01-23 15:13 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> -    }
<img width="1122" alt="Screenshot 2025-01-23 at 10 09 40 AM" src="https://github.com/user-attachments/assets/ab54e0df-3262-42d2-aa20-ba1f86999959" />
This is the only relevant scenario that `SQLException` matters. It made me hesitate a lot. You can experiment by keep the statement of `MongoConnection#createClob()` (which throws `NotYetImplementedException which doesn't inherit from `SQLException`) by running integration test to see. It would fail due to the above weird logic.

2025-01-23 15:15 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +            return new MongoDatabaseMetaData(this, versionText, versionArray.get(0), versionArray.get(1));
Good question! I think it depends on how the method is gonna used. If it is used more than once in one JVM process, we definitively need to cache it somewhere. But from Hibernate's codebase, it is only invoked once during dialect creation, so currently it seems unnecessary to add cache of it.

2025-01-23 17:51 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +                    mongoClient.getDatabase("admin").runCommand(new BsonDocument("buildinfo", new BsonInt32(1)));
good catch!

2025-01-23 17:59 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/dialect/MongoDialect.java
>       *
removed

2025-01-23 18:05 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
I agree. I also added `isWrapperFor` to `PreparedStatement` PR.

2025-01-23 18:29 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +            return false;
Good point and catch! Originally when I implemented this PR (long time ago) I still harboured the mindset to integrate with Hibernate as seamlessly as possible. So if the method is used in Hibernate, I tried my best to act elegantly. Back then I think returning dummy result is still better than throwing exception.

But since last Statement PR, I had changed my mind. We simply remove any method we don't want to support. The `getTables()` method is only invoked during Hibernate's DDL phase so is irrelevant to us. I checked in POC project and found it won't hinder our MongoDB index / unique constraint requirements, so we can safely remove it and the corresponding ResultSetAdapter.

2025-01-23 18:54 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +                    mongoClient.getDatabase("admin").runCommand(new BsonDocument("buildinfo", new BsonInt32(1)));
oh, I forgot that.

2025-01-23 19:01 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
We don't have a ticket for this. But we can copy the way from Java driver. I assume it is not complicated. But there is a subtle difference. The above versions are for JDBC Driver (we don't have vanilla JDBC Driver) not for our dialect library product versions, right?

For that reason, I used humble `MongoDB Java Driver JDBC Adapter` as the driver name to emphasize it is not an indepedent JDBC Driver project. Not sure we could use our dialect product version as an emulated JDBC adapter's versions though.

2025-01-23 19:19 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    public boolean storesUpperCaseIdentifiers() {
If you could succeed removing the methods while integration testing still work, that is sign the method in question might not be needed (at least for the Hibernate version in question).

I implemented as many methods as possible (many of them are irrelevant) so our product is more robust; but I also see the point to remove ones which won't trigger `SessionFactoryTests` integration testing failure.

I'd removed `getTypeInfo` (so we could remove `ResultSetAdapter`) in previous comments. Let us remove the following methods additionally:

- storesUpperCaseIdentifiers()
- storesLowerCaseIdentifiers()
- storesMixedCaseIdentifiers()
- supportsMixedCaseQuotedIdentifiers()
- storesUpperCaseQuotedIdentifiers()
- storesLowerCaseQuotedIdentifiers()
- storesMixedCaseQuotedIdentifiers()
- supportsRefCursors()

The decision is hard for I am not sure whether removal will make other Hibernate ORM version fail to work. Maybe in the future our evergreen should have another matrix dimention: Hibernate versions.

2025-01-23 19:22 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
The original intention is to provide JDBC version context for each method we support. So in the future when JDBC and Hibernate evolves, new methods might be appended to the end in the context of new JDBC version.

I have no objection to remove such markers, which is another kind of manual labour for coder.

2025-01-23 19:25 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
Good point! It is also related to the following method in `MongoConnection`:
```
public PreparedStatement prepareStatement(String mql, int resultSetType, int resultSetConcurrency);
```
which will be done in ResultSet implementation PR in the future.

2025-01-23 19:35 UTC, NathanQingyangXu commented on src/test/resources/logback-test.xml
> +    <logger name="org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator" level="debug" additivity="true"/>
Good catch! Actually it was added only for integration testing (the PR was created prior to the integration testing and unit testing separation). Now I moved it to integration testing (it is no relevant to pure unit testing though after this metadata PR which introduces external 'admin' dependency).

2025-01-23 19:40 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoConnectionTests.java
> +        class TransactionTests {
You are right. I might have screwed up during syncing up with latest main branch.

2025-01-23 19:57 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoConnection.java
> +            throw new SQLException("Failed to get metadata", e);
Great point! I added as suggested.

2025-01-23 20:41 UTC, NathanQingyangXu commented on src/test/java/com/mongodb/hibernate/jdbc/MongoConnectionTests.java
>              }
I added similar stuff to `MongoConnectionTests` to ensure consistency with `MongoStatementTest`. Yeah, I should have checked more despite this PR is super old.

2025-01-23 21:09 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
I found Jeff has created a ticket at https://jira.mongodb.org/browse/HIBERNATE-34. Guess that ticket will take care of passing the build version info to MongoClient and then all the way to MongoDatabaseMetadata? If so, I'll add some code comment.
I think you are right, the JDBC Driver version should correspond to our project build version.

2025-01-23 21:17 UTC, jyemin commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
That ticket is unrelated.  It's about passing the library version all the way to the server, so that we can get Atlas telemetry on what versions of this library people are using.

2025-01-23 21:20 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
I added a comment to to the https://jira.mongodb.org/browse/HIBERNATE-34 ticket to remind that its scope should include providing metadata not only to MongoDB server, but also to our hibernate dialect user.

https://jira.mongodb.org/browse/HIBERNATE-34?focusedCommentId=7016294&focusedId=7016294&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-7016294

2025-01-24 01:04 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    }
Thank you for removing them.

> provide JDBC version context for each method we support

All we need to get to those comments is jump to the source code of the JDBC interface we implement.

2025-01-24 16:25 UTC, stIncMale commented on src/test/java/com/mongodb/hibernate/jdbc/MongoConnectionTests.java
>              }
The change in https://github.com/mongodb/mongo-hibernate/pull/22/commits/cd9517c4f8e88aa58d23705e343318733ef780af is better than what I was thinking about. But given this change, we no longer need the following tests:

- `MongoConnectionTests.TransactionTests.SetAutoCommitTests.testSQLExceptionThrowWhenCalledOnClosedConnection`
- `MongoConnectionTests.TransactionTests.CommitTests.testSQLExceptionThrowWhenCalledOnClosedConnection`
- `MongoConnectionTests.TransactionTests.RollbackTests.testSQLExceptionThrowWhenCalledOnClosedConnection`
- `MongoConnectionTests.GetMetaDataTests.testSQLExceptionThrownWhenConnectionClosed`

We additionally should remove the following tests, because they don't verify what they are supposed to verify, as the corresponding methods are not overridden in `MongoConnection`:

- `MongoConnectionTests.TransactionTests.TransactionIsolationLevelTests.testSQLExceptionThrowWhenCalledOnClosedConnection`
- `MongoConnectionTests.TransactionTests.TransactionIsolationLevelTests.testSQLExceptionThrowWhenCalledOnClosedConnection`

2025-01-24 16:50 UTC, stIncMale requested changes
The last reviewed commit is d3cc51d1f9094039182256b416329671b48b56e4.

2025-01-24 16:50 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        return 0; // // to be implemented in scope of https://jira.mongodb.org/browse/HIBERNATE-34
Instead of leaving arbitrary-form comments, and not having the corresponding tickets refer back to them, we should to what we agreed to in the Java driver repo:

- The comments are `// TODO-<ticket number> <any additional text>`, for example, `// TODO-HIBERNATE-34`
- The description of the https://jira.mongodb.org/browse/HIBERNATE-34 ticket should mention that resolving all the `TODO-HIBERNATE-34` comments is in scope of the ticket.

I'll apply this approach to the `main` branch.

2025-01-24 19:34 UTC, jyemin approved these changes
I don't plan to review this further so LGTM-ing to allow merge when Valentin approves.

2025-01-27 21:30 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        return 0; // // to be implemented in scope of https://jira.mongodb.org/browse/HIBERNATE-34
Given Hibernate-34 has been merged, I made further code changes to parse the version text in `BuildConfig.VERSION` to populate the two driver version numbers, together with a unit testing case.

Not sure whether it is over-engineering, but it seems good move.

2025-01-28 07:40 UTC, stIncMale requested changes
The last reviewed commit is a3ae08390b4edd90ca5b1bd421e1198b34bb4007.

2025-01-28 07:40 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    record VersionNumPair(int majorVersion, int minVersion) {}
After writing a few comments and realizing that there are many more to be written, I created a commit with my proposal, as that's faster: https://github.com/stIncMale/mongo-hibernate/commit/36919ae83f1882c2c77fecdd81747bbd46f946b8.

2025-01-28 07:41 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +            }
See https://github.com/mongodb/mongo-hibernate/pull/22#discussion_r1931657482 for my suggestion on how to proceed.

2025-01-28 07:41 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        var tokenizer = new StringTokenizer(versionText, ".");
See https://github.com/mongodb/mongo-hibernate/pull/22#discussion_r1931657482 for my suggestion on how to proceed.

2025-01-28 14:23 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        var tokenizer = new StringTokenizer(versionText, ".");
`StringTokenizer` is faster so that was the reason I chose it, but I agree perf opt is not important here.

2025-01-28 14:32 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        var tokenizer = new StringTokenizer(versionText, ".");
It is still used in Hibernate ORM, e.g. https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/sql/Template.java. I agree perf opt is not as important as there, but I hope we still retain the possibility to use it in scenario where it still shines.

2025-01-28 14:57 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +            }
Wonderful! I made changers as you suggested intact.

Just made one minor change from
```
String[] parts = versionText.split("[.\\-]", 3);
```
to
```
String[] parts = versionText.split("[-.]", 3);
```
for if `-` appears at the beginning of RegEx, no escaping is required. Also, we have unit testing case to protect us.

2025-01-28 14:59 UTC, NathanQingyangXu commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +    record VersionNumPair(int majorVersion, int minVersion) {}
adopted. excellent!

2025-01-28 18:59 UTC, NathanQingyangXu commented on src/test/resources/hibernate.properties
> +hibernate.boot.allow_jdbc_metadata_access=false
yeah, separating unit and integration testings make lots of sense for they have different requirements and specialities. In the future we might introduce Hibernate's integration testing library [(hibernate-testing)](https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-testing) which only makes sense in integration testing context.

2025-01-28 19:20 UTC, stIncMale requested changes
The last reviewed commit is b229a4db81c0be7ec1b43817c2d9102f5d0c8a1a.

2025-01-28 19:20 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +            }
👍

2025-01-28 19:23 UTC, stIncMale commented on src/main/java/com/mongodb/hibernate/jdbc/MongoDatabaseMetaData.java
> +        var tokenizer = new StringTokenizer(versionText, ".");
I currently can't see where in Mongo Hibernate this could make a measurable difference, but if it ever does, we should at least consider it.

2025-01-28 20:19 UTC, stIncMale approved these changes
The last reviewed commit is e74ee15c32a555dd01de8bbf9e5df8ede7382a15.

2025-01-28 20:53 UTC, merged