some improvements to testing
mongodb/mongo-hibernate pull request #23
Opened 2024-12-27 16:38 UTC by NathanQingyangXu

- separate unit and integration tests as per gradle's official doc (https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests)
- tweak evergreen configurations accordingly (now only `run-integration-test` task will be applied `mongo-orchestration` dependencies)
- update README.md by adding a new `Testing` section
- minor dependency version bumping

2025-01-02 19:06 UTC, NathanQingyangXu commented
@katcharov, feel free to take a look for it involves some `evergreen` changes (I tested locally).

2025-01-02 19:16 UTC, jyemin commented
I went ahead and made @katcharov primary on this one

2025-01-13 22:19 UTC, katcharov requested changes

2025-01-13 22:19 UTC, katcharov commented on README.md
> +Per best practice, we maintain separate directories for unit and integration testings:
```suggestion
This project uses separate directories for unit and integration tests:
```

2025-01-13 22:19 UTC, katcharov commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
In the Java driver, we pass in the tests that we would like to run, see [here for example](https://github.com/mongodb/mongo-java-driver/blob/main/.evergreen/.evg.yml#L875). Let's do the same here.

2025-01-13 22:19 UTC, katcharov commented on README.md
> +Integration tests will connect to a MongoDB deployment. You may change the default [MongoDB connection string](https://www.mongodb.com/docs/manual/reference/connection-string/) configured as below at
```suggestion
Integration tests require a MongoDB deployment. You may change the default [MongoDB connection string](https://www.mongodb.com/docs/manual/reference/connection-string/), below, in [hibernate.properties](src/integrationTest/resources/hibernate.properties):
```

2025-01-13 22:19 UTC, katcharov commented on README.md
> +It would be highly helpful to refer to the following awesome articles or resources when need arises:
```suggestion
```
I don't think we need to comment on this - if the documents have been included under references in the main readme, they must be helpful and good.

2025-01-13 22:19 UTC, katcharov commented on README.md
> +An internal CI/CD pipeline is based on an open-source project [evergreen](https://github.com/evergreen-ci/evergreen), a distributed continuous integration system from MongoDB. The corresponding everg
```suggestion
This project uses [evergreen](https://github.com/evergreen-ci/evergreen), a distributed continuous integration system from MongoDB. The evergreen configuration is in the [.evergreen](/.evergreen) directory.
```

2025-01-13 22:19 UTC, katcharov commented on README.md
> +### Testing
We could give the CLI command to run all the tests, somewhere in this section

2025-01-15 14:30 UTC, NathanQingyangXu commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
I studied the example, but it is not applicable to this project. Java driver is a multi-module projects but currently this project has only one module. Even in the future we refactor it into multi-module project, I doubt whether we need to separete them. Java driver project parameterized module maybe due to performance reason (parallism), I guess.
@jyemin , how do you think?

2025-01-15 14:50 UTC, NathanQingyangXu commented on README.md
> +### Testing
good idea. I added gradle command usage examples for both tests.

2025-01-15 14:51 UTC, NathanQingyangXu commented on README.md
> +jakarta.persistence.jdbc.url={your_mongodb_connection_string}
I also changed the above properties using placeholder. Repeating existing property seems not to make sense (which is a moving target).

2025-01-15 16:30 UTC, jyemin commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
It seems to be that `test` is sufficient, since we want to run them all.  Until very recently that's what we did for the driver (and yes, we did split it out recently only to increase parallelism on Evergreen)

2025-01-15 17:20 UTC, katcharov reviewed
.

2025-01-15 18:05 UTC, NathanQingyangXu commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
yeah, after the changes as per https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests, the `test` will focus on Unit Test and `integrationTest` will focus on integration test, just as what I've put in README.md regarding  the two gradle usages.

2025-01-15 18:50 UTC, NathanQingyangXu commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
@jyemin , what is your preference? The gist of the separation is to plan for custmized development for the two kinds of tests. Currently, `unit test` won't launch `mongo-orchestration` task and that is one of the possible divergence.
If we merge the two test scripts into one generic (and relying on a gradle task parameter), it seems to defeat the purpose of the gist of this PR. For one thing, there are other important script content difference, e.g. we need to log topology info only in `test-integration-tests.sh`, but we don't need to log in `test-unit-tests.sh`.

2025-01-15 19:24 UTC, katcharov commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
If these files are being created because we expect to add differences in an ensuing PR, then that is a fine reason to have them, though it would be helpful to know what the expected divergences are. (I don't see the harm of logging an empty version/topology.) I'll leave this thread unresolved in case you still wanted feedback from others.

2025-01-15 19:24 UTC, katcharov approved these changes

2025-01-15 19:54 UTC, jyemin commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
The files are so small at this point that the duplication doesn't particularly bother me.

2025-01-15 20:14 UTC, NathanQingyangXu commented on .evergreen/run-unit-tests.sh
> +./gradlew -PjavaVersion=${JAVA_VERSION} --stacktrace --info --continue clean test
> @rozza , I would appreciate it if you shed your insight here.

nvm. I think this PR is simple. I'll go ahead merging it. No need bothering you.

2025-01-15 20:14 UTC, merged